import { RefreshCcw } from 'lucide-react';
import type { CharacterDoc, DerivedSheet, EffectOrigin } from '@/engine/types';
import { ChoicePromptRenderer } from './ChoicePromptRenderer';

/**
 * The choices (skills, languages, fighting styles, ASI/feat picks…) generated by
 * one origin, rendered right where that origin lives — under the race card, the
 * class card, etc. — instead of a single flat list where you can't tell what
 * produced each pick. Shows unmade prompts and made choices (with a "change"),
 * and skips the options-less subclass pointer since the subclass picker sits
 * inline already.
 */
export function OriginChoices({
  sheet,
  doc,
  update,
  match,
}: {
  sheet: DerivedSheet;
  doc: CharacterDoc;
  update: (recipe: (d: CharacterDoc) => void) => void;
  match: (origin: EffectOrigin) => boolean;
}) {
  const pending = sheet.pending.filter(
    (p) => match(p.origin) && !(p.kind === 'generic' && p.options.length === 0),
  );
  const resolved = sheet.resolvedChoices.filter((r) => match(r.prompt.origin));
  if (pending.length === 0 && resolved.length === 0) return null;

  return (
    <div className="mt-2 flex flex-col gap-2 border-t border-surface-2/40 pt-2">
      {pending.map((prompt) => (
        <div key={prompt.id} data-pending-choice="">
          <ChoicePromptRenderer
            prompt={prompt}
            value={doc.choices[prompt.id]}
            onChange={(v) => update((d) => void (d.choices[prompt.id] = v))}
          />
        </div>
      ))}
      {resolved.map(({ prompt, selected }) => (
        <div
          key={prompt.id}
          className="flex items-center justify-between gap-2 rounded-lg bg-surface-2/60 px-3 py-2 text-sm"
        >
          <div className="min-w-0">
            <div className="truncate">{prompt.label}</div>
            <div className="truncate text-xs text-ink-muted">{selected.join(', ')}</div>
          </div>
          <button
            type="button"
            title="Change this pick"
            onClick={() =>
              update((d) => {
                delete d.choices[prompt.id];
                // dependent follow-up choices (ASI feat picks etc.) reset too
                for (const key of Object.keys(d.choices)) {
                  if (key.startsWith(`${prompt.id}:`)) delete d.choices[key];
                }
              })
            }
            className="flex shrink-0 items-center gap-1 rounded border border-surface-2 px-2 py-1 text-xs text-ink-muted hover:text-ink"
          >
            <RefreshCcw size={12} /> change
          </button>
        </div>
      ))}
    </div>
  );
}
