import { Info, RefreshCcw } from 'lucide-react';
import type { Entity } from '@/data5e/copyMod';
import type { EntityRegistry } from '@/data5e/normalize';
import { filterByRulesVersion, type RulesVersion } from '@/data5e/rulesVersion';
import type {
  CharacterDoc,
  ChoiceOption,
  ChoicePrompt,
  DerivedSheet,
  EffectOrigin,
} from '@/engine/types';
import { EntityInfoSheet } from '@/ui/EntityInfoSheet';
import { ChoicePromptRenderer } from './ChoicePromptRenderer';

/**
 * Hide feat options that don't belong to the character's rules version (the
 * engine builds the ASI feat list from every edition). Keeps any already-chosen
 * or unresolvable option so a picked feat never vanishes.
 */
function filterFeatPrompt(
  prompt: ChoicePrompt,
  registry: EntityRegistry,
  version: RulesVersion,
  value: string[] | string | number | undefined,
): ChoicePrompt {
  const selected = new Set(
    Array.isArray(value) ? value.map(String) : value !== undefined ? [String(value)] : [],
  );
  const feats: Entity[] = [];
  const resolvedIds = new Set<string>();
  for (const o of prompt.options) {
    const [name, source] = o.id.split('|');
    const feat = name !== undefined ? registry.get('feat', name, source) : undefined;
    if (feat !== undefined) {
      feats.push(feat);
      resolvedIds.add(o.id);
    }
  }
  const kept = new Set(
    filterByRulesVersion(feats, version).map((f) =>
      `${String(f.name)}|${String(f.source)}`.toLowerCase(),
    ),
  );
  const options = prompt.options.filter(
    (o) => selected.has(o.id) || !resolvedIds.has(o.id) || kept.has(o.id),
  );
  return { ...prompt, options };
}

/** ⓘ full-description drawer for a feat option (id is `name|source`). */
function featOptionInfo(registry: EntityRegistry) {
  return (o: ChoiceOption) => {
    const [name, source] = o.id.split('|');
    const feat = name !== undefined ? registry.get('feat', name, source) : undefined;
    if (feat === undefined) return null;
    return (
      <EntityInfoSheet
        type="feat"
        entity={feat}
        subtitle={`${String(feat.name)} · ${String(feat.source)}`}
        trigger={
          <button
            type="button"
            aria-label={`${o.label} details`}
            title="Full description"
            className="rounded-full p-1 text-ink-muted hover:bg-surface-2 hover:text-ink"
          >
            <Info size={16} />
          </button>
        }
      />
    );
  };
}

/**
 * The choices (skills, languages, fighting styles, ASI/feat picks…) generated by
 * one origin, rendered right where that origin lives — under the race card, the
 * class card, etc. — instead of a single flat list where you can't tell what
 * produced each pick. Shows unmade prompts and made choices (with a "change"),
 * and skips the options-less subclass pointer since the subclass picker sits
 * inline already.
 */
export function OriginChoices({
  sheet,
  doc,
  update,
  match,
  registry,
}: {
  sheet: DerivedSheet;
  doc: CharacterDoc;
  update: (recipe: (d: CharacterDoc) => void) => void;
  match: (origin: EffectOrigin) => boolean;
  /** Enables ⓘ full-description drawers on feat options when provided. */
  registry?: EntityRegistry | null;
}) {
  const pending = sheet.pending.filter(
    (p) => match(p.origin) && !(p.kind === 'generic' && p.options.length === 0),
  );
  const resolved = sheet.resolvedChoices.filter((r) => match(r.prompt.origin));
  if (pending.length === 0 && resolved.length === 0) return null;

  const featInfo = registry != null ? featOptionInfo(registry) : undefined;

  return (
    <div className="mt-2 flex flex-col gap-2 border-t border-surface-2/40 pt-2">
      {pending.map((prompt) => {
        const shown =
          prompt.kind === 'feat' && registry != null
            ? filterFeatPrompt(prompt, registry, doc.rulesVersion, doc.choices[prompt.id])
            : prompt;
        return (
          <div key={prompt.id} data-pending-choice="">
            <ChoicePromptRenderer
              prompt={shown}
              value={doc.choices[prompt.id]}
              onChange={(v) => update((d) => void (d.choices[prompt.id] = v))}
              renderOptionInfo={prompt.kind === 'feat' ? featInfo : undefined}
            />
          </div>
        );
      })}
      {resolved.map(({ prompt, selected }) => (
        <div
          key={prompt.id}
          className="flex items-center justify-between gap-2 rounded-lg bg-surface-2/60 px-3 py-2 text-sm"
        >
          <div className="min-w-0">
            <div className="truncate">{prompt.label}</div>
            <div className="truncate text-xs text-ink-muted">{selected.join(', ')}</div>
          </div>
          <button
            type="button"
            title="Change this pick"
            onClick={() =>
              update((d) => {
                delete d.choices[prompt.id];
                // dependent follow-up choices (ASI feat picks etc.) reset too
                for (const key of Object.keys(d.choices)) {
                  if (key.startsWith(`${prompt.id}:`)) delete d.choices[key];
                }
              })
            }
            className="flex shrink-0 items-center gap-1 rounded border border-surface-2 px-2 py-1 text-xs text-ink-muted hover:text-ink"
          >
            <RefreshCcw size={12} /> change
          </button>
        </div>
      ))}
    </div>
  );
}
